import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/globals.css";

import SessionProvider from "./ui/session-provider";
import { getSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <SessionProvider session={session}> */}
          {children}
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
